### ISSUE TITLE
URLOutputStream NoClassDefFoundError

### ISSUE THREAD

**Issue by oche-jay** [MicroFocus/octane-cucumber-jvm#5] opened 2019-07-18 09:38 UTC
Some changes introduced in Cucumber 4.2.2 have broken the compatibility with the OctaneGherkinFormatter plugin, unfortunately.

After upgrading our framework to  cucmber-jvm version 4.2.2, we get the following error
>    cucumber.runtime.CucumberException: java.lang.NoClassDefFoundError: cucumber/runtime/io/URLOutputStream

A quick investigation shows that Cucumber have moved the `URLOutputStream` class to another package and made the access package-private.

https://github.com/cucumber/cucumber-jvm/commit/eb1a90bd5488421b06acfab4d2b32bf851cdf1db#diff-65fe24f46bdf791ab35eaaca6228df3d

**Comment by sharonvardi** [comment] 2019-07-18 10:39
Hi @oche-jay!
What version of octane-cucumber-jvm do you use?

**Comment by oche-jay** [comment] 2019-07-18 10:41
12.60.48-SNAPSHOT

**Comment by oche-jay** [comment] 2019-07-18 10:41
Thanks for the quick response

**Comment by yuval-koren** [comment] 2019-07-30 15:53
Hi @oche-jay,
Thanks for your input. 
Indeed the compatibility is broken. 
We will fix this in the near future. 
The timing really depends on how small the fix is.

**Comment by eyal666** [comment] 2020-05-18 11:47
Hi @oche-jay,
The issue is fixed on version 15.1.0.
You can find the changelog [here](https://github.com/MicroFocus/octane-cucumber-jvm/pull/6#issue-416198417).
Thank you.

**Closed as completed by eyal666** 2020-05-18 11:47 UTC
